# Generated by Django 4.1.3 on 2023-07-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_entry_title_entry_mood_entry_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
