# Generated by Django 4.1.3 on 2023-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_entry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
