# Generated by Django 4.1.3 on 2023-07-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_entry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='created_at',
        ),
    ]
